# Generated by Django 4.2.5 on 2023-09-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='type',
            field=models.CharField(choices=[('Музыка', 'Музыка'), ('Реплики персонажей', 'Реплики персонажей')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='type',
            field=models.CharField(choices=[('Синематики', 'Синематики'), ('Игровой процесс', 'Игровой процесс')], max_length=255, null=True),
        ),
    ]
